using BAMP.SyncFix;
using BigAmbitionsMP;
using Newtonsoft.Json;
using System.Reflection;
int passed=0;
void Check(bool ok,string name){if(!ok)throw new Exception(name);passed++;Console.WriteLine("PASS: "+name);}
void Throws(Action a,string name){try{a();throw new Exception("Expected failure: "+name);}catch(InvalidDataException){Check(true,name);}}
var gate=new StreamGate();
Check(gate.Accept("p","a",10),"initial stream");
Check(!gate.Accept("p","a",9)&&!gate.Accept("p","a",10),"late and duplicate frames ignored");
Check(gate.Accept("p","b",1)&&!gate.Accept("p","a",999),"reconnect accepts new sequence and retires old stream");
gate.Clear();Check(gate.Accept("p","a",1),"world reset clears stream state");
Throws(()=>SafetyCore.ValidateLength(new byte[2],3),"truncated save refused");
Throws(()=>SafetyCore.ValidateLength(new byte[2],0),"missing length refused");
SafetyCore.ValidateLength(new byte[2],2);Check(true,"matching save accepted");
Check(!SafetyCore.Finite(float.NaN)&&!SafetyCore.Finite(float.PositiveInfinity)&&SafetyCore.InitialCapacity(int.MaxValue)==65536,"nonfinite and allocation guards");
var rows=new[]{"first",null,"", "second", "third"};
Check(SafetyCore.RemainingAfter(rows,1,s=>s!="").SequenceEqual(new[]{"","second","third"}),"partial cargo error returns only rows without completed ACKs");
Check(SafetyCore.RemainingAfter(new[]{"same","same","last"},2,s=>true).SequenceEqual(new[]{"last"}),"identical cargo rows counted separately");
using(var output=new MemoryStream()){SafetyCore.CopyBounded(new MemoryStream(new byte[]{1,2,3}),output);Check(output.ToArray().SequenceEqual(new byte[]{1,2,3}),"bounded decoder keeps valid bytes");}
using(var output=Stream.Null)Throws(()=>SafetyCore.CopyBounded(new RepeatedStream(SafetyCore.MaxMessage+1L),output),"oversized decoded message refused");
var dir=Path.Combine(Path.GetTempPath(),"bamp-sync-test-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);
try{
 var p=Path.Combine(dir,"save.hsg");SafetyCore.AtomicSavePair(p,new byte[]{1},"old");SafetyCore.AtomicSavePair(p,new byte[]{2},"new");
 Check(File.ReadAllBytes(p)[0]==2&&File.ReadAllText(p+".meta")=="new","save and metadata replaced together");
 File.WriteAllBytes(p+".bamp-pair-old",new byte[]{1});File.WriteAllText(p+".meta.bamp-pair-old","old");File.WriteAllText(p+".bamp-pair","11");
 SafetyCore.RecoverPair(p);Check(File.ReadAllBytes(p)[0]==1&&File.ReadAllText(p+".meta")=="old"&&!File.Exists(p+".bamp-pair"),"interrupted save pair recovers both prior files");
 File.WriteAllText(p+".bamp-pair","00");SafetyCore.RecoverPair(p);Check(!File.Exists(p)&&!File.Exists(p+".meta"),"interrupted first save removes incomplete pair");
 SafetyCore.AtomicText(p,"stable");try{SafetyCore.AtomicBytes(p,null);}catch(ArgumentNullException){}Check(File.ReadAllText(p)=="stable","invalid write preserves prior file");
}finally{Directory.Delete(dir,true);}
var money=new MoneyAdjustPayload{To="host",Amount=50,Reason="test"};Wire.Ensure(money);Wire.ApplyMoney(money);Wire.ApplyMoney(JsonConvert.DeserializeObject<MoneyAdjustPayload>(JsonConvert.SerializeObject(money)));
Check(SaveGameManager.Current.Money==1050&&MPHub.Applies==1,"money replay across serialization changes balance once");
SaveGameManager.Current=new GameInstance{Money=1050,modData=new(SaveGameManager.Current.modData)};Wire.ApplyMoney(money);
Check(MPHub.Applies==1,"saved journal prevents replay after reload");
money=new MoneyAdjustPayload{To="host",Amount=5};Wire.Ensure(money).World="other";Wire.ApplyMoney(money);Check(MPHub.Applies==1,"money from another world ignored");
var groups=(Dictionary<string,MergerGroupInfo>)MPServer.Fields["_groupInfo"];groups["g"]=new MergerGroupInfo{MemberPids=new(){"host","friend"}};Wire.Assign(groups["g"],new WireStamp{Id="generation"});MergerSync.MyGroupId="g";MergerSync.Membership["friend"]="g";
var wallet=new MergerWalletDeltaPayload{PlayerId="friend",Amount=5};Wire.Ensure(wallet);Wire.ApplyWallet(wallet);Wire.ApplyWallet(wallet);Check(MPServer.WalletCalls==1,"wallet operation applied once");
var stale=new MergerWalletDeltaPayload{PlayerId="friend",Amount=5};Wire.Ensure(stale);Wire.Assign(groups["g"],new WireStamp{Id="new-generation"});Wire.ApplyWallet(stale);Check(MPServer.WalletCalls==1,"wallet from previous membership generation refused");
MergerSync.MyGroupId="";MergerSync.Membership.Clear();MPServer.Cash["friend"]=1000;
MoneyTransport.Context="deal";MoneyTransport.Deliver("friend",-200,"gift",true);MoneyTransport.Deliver("friend",-200,"gift",true);
Check(Wire.Journal().Count(p=>p.Key.StartsWith("money-out|"))==1&&MoneyTransport.Reserved("friend")==200,"offer retry reuses delivery ID and reserves once");
var outgoing=(MoneyAdjustPayload)MPServer.Sent.Last().Item3;
MPConfig.PlayerId="friend";var receipt=new MoneyReceipt{PlayerId="friend",Id=Wire.Meta(outgoing).Id};var e=MessageEnvelope.Create((MessageType)223,"friend",receipt);MPConfig.PlayerId="host";
Check(MoneyTransport.Consume(e,"friend"),"receipt recognized");GameStatePatcher.Drain();MoneyTransport.Consume(e,"friend");GameStatePatcher.Drain();
Check(MPServer.Cash["friend"]==1000&&MoneyTransport.Reserved("friend")==200,"duplicate receipts never debit cached balance or prematurely free reserve");
MPConfig.PlayerId="friend";var ce=MessageEnvelope.Create(MessageType.CashSync,"friend",new CashSyncPayload{PlayerId="friend",Money=800});MPConfig.PlayerId="host";
Check(!MoneyTransport.Consume(ce,"friend"),"fresh cash continues original dispatcher");GameStatePatcher.Drain();Check(MoneyTransport.Reserved("friend")==0,"newer cash confirmation releases reserve");
Check(Wire.Scan("money-out|").Length==0&&Wire.Scan("money-closed|").Length==1,"confirmed delivery leaves hot retry queue but retains reconnect recovery");
Check(MoneyTransport.Consume(ce,"friend"),"duplicate cash snapshot blocked");
var invalidReceipt=MessageEnvelope.Create((MessageType)223,"host",new MoneyReceipt{PlayerId="intruder",Id=Wire.Meta(outgoing).Id});MoneyTransport.Consume(invalidReceipt,"friend");Check(GameStatePatcher.Pending.Count==0,"spoofed receipt cannot acknowledge another player");
var loans=(List<LoanEntry>)MPServer.Fields["_hostLoans"];loans.Add(new LoanEntry{Id="loan",Borrower="friend",Remaining=500});MPServer.Cash["friend"]=100;
object[] repaymentArgs={new LoanRepayPayload{Id="loan",From="friend",Amount=200},null};var method=typeof(RepaymentSafety).GetMethod("Prefix",BindingFlags.Static|BindingFlags.NonPublic)!;
Check(!(bool)method.Invoke(null,repaymentArgs),"unaffordable early repayment refused before effects");
repaymentArgs[0]=new LoanRepayPayload{Id="loan",From="friend",Amount=float.NaN};Check(!(bool)method.Invoke(null,repaymentArgs),"NaN early repayment refused");
SaveGameManager.Current=new GameInstance();MoneyTransport.Reset();StorageProgress.Reset();WorldStreams.Reset();
SaveGameManager.Current.modData["GoingPublic.SyncFix.1"]="{\"money|old\":\"done\"}";
Check(Wire.Result("money|old")=="done"&&!SaveGameManager.Current.modData.ContainsKey("GoingPublic.SyncFix.1"),"legacy journal migrated without losing replay tombstones");
for(int i=0;i<4000;i++)Wire.Remember("record|"+i,"done");
var beforeBuckets=new Dictionary<string,string>(SaveGameManager.Current.modData);Wire.Remember("another-record","done");
Check(SaveGameManager.Current.modData.Count(p=>!beforeBuckets.TryGetValue(p.Key,out var prior)||prior!=p.Value)==1,"journal update serializes one bucket rather than all history");
SaveGameManager.Current.modData=new Dictionary<string,string>(SaveGameManager.Current.modData);Check(Wire.Result("record|3000")=="done","journal cache invalidates after save rollback/replacement");
SaveGameManager.Current=new GameInstance();
var placeA=new BigAmbitions.Items.CargoInstance{Name="A"};var placeB=new BigAmbitions.Items.CargoInstance{Name="B"};
var requestA=new StorageOpPayload{Ctx="placereduce",PlayerId="host"};var requestB=new StorageOpPayload{Ctx="placereduce",PlayerId="host"};
MPServer.Fields["_pendingPlace"]=placeA;StorageProgress.Sending(requestA);MPServer.Fields["_pendingPlace"]=placeB;StorageProgress.Sending(requestB);
var replyA=new StorageResPayload();Wire.Assign(replyA,Wire.Meta(requestA));var prev=StorageProgress.Placement(replyA);
Check(ReferenceEquals(MPServer.Fields["_pendingPlace"],placeA),"late placement response uses its original instance");StorageProgress.RestorePlacement(prev);
Check(ReferenceEquals(MPServer.Fields["_pendingPlace"],placeB),"processing one response preserves another pending placement");
StorageProgress.Reset();prev=StorageProgress.Placement(replyA);Check(MPServer.Fields["_pendingPlace"]==null,"after reload placement falls back to return instead of using an unrelated item");StorageProgress.RestorePlacement(prev);
int replicas=0,effects=0;
Hooks.Calls["StorageSync.EchoBuildingReplica"]=a=>{replicas++;return null;};
Hooks.Calls["StorageSync.OnTakeResult"]=a=>{effects++;StorageProgress.Fail();return null;};
var result=new StorageResPayload();Wire.Ensure(result);var frame=StorageProgress.Begin(result);StorageProgress.Echo(result);StorageProgress.Take(result);StorageProgress.End(frame);
Check(Wire.Result("storage-result|"+Wire.Meta(result).Id)==null,"caught effect failure is not falsely marked consumed");
Hooks.Calls["StorageSync.OnTakeResult"]=a=>{effects++;return null;};
frame=StorageProgress.Begin(result);StorageProgress.Echo(result);StorageProgress.Take(result);StorageProgress.End(frame);
Check(replicas==1&&effects==2&&Wire.Result("storage-result|"+Wire.Meta(result).Id)=="consumed","retry runs only unfinished storage stage");
result=new StorageResPayload();Wire.Ensure(result);Hooks.Calls["StorageSync.OnTakeResult"]=a=>{StorageProgress.Commit();StorageProgress.Fail();return null;};
frame=StorageProgress.Begin(result);StorageProgress.Take(result);StorageProgress.End(frame);Check(Wire.Result("storage-result|"+Wire.Meta(result).Id)=="consumed","post-mutation UI failure does not replay completed economic effect");
int sent=0;MergerOutbox.Begin();MergerOutbox.Queue(()=>sent++);MergerOutbox.DeferPersist();Check(sent==0,"merger exposes no remote messages during mutation");MergerOutbox.Cancel();Check(sent==0&&MPSaveCoordinator.Persists==0,"failed merger discards messages and intermediate persistence");
MergerOutbox.Begin();MergerOutbox.Queue(()=>sent++);MergerOutbox.DeferPersist();MergerOutbox.Commit();Check(sent==1&&MPSaveCoordinator.Persists==1,"successful merger persists then releases buffered messages");
var authority=new CustomerSimAuthorityPayload{AddressKey="shop",SimulatorPid="simA"};MessageEnvelope.Create(MessageType.MoneyAdjust,"host",authority);
var visits=new CustomerVisitStatePayload{AddressKey="shop",SimulatorPid="simA"};MessageEnvelope.Create(MessageType.MoneyAdjust,"host",visits);Check(WorldStreams.ValidSimulator(visits,false),"current customer authority generation accepted");
MessageEnvelope.Create(MessageType.MoneyAdjust,"host",new CustomerSimAuthorityPayload{AddressKey="shop",SimulatorPid="simB"});
Check(!WorldStreams.ValidSimulator(visits,false),"late visits from previous simulator refused");MPServer.Fields["_awaitFinalFrom"]="simA";Check(WorldStreams.ValidSimulator(visits,true),"explicitly awaited old simulator final handoff preserved");
SaveGameManager.Current=new GameInstance();MoneyTransport.Reset();LoanPeriods.Reset();UnityEngine.Time.unscaledTime=10;GameStateReader.Day=1;MPServer.Fields["_lastDay"]=-1;
loans.Clear();loans.Add(new LoanEntry{Id="period-loan",Borrower="friend",Lender="host",Remaining=500,DailyPayment=50,DailyInterest=5});LoanPeriods.Tick();
Check(Wire.Result("loan-period-cursor")=="1","loan cursor initialized to live day");
UnityEngine.Time.unscaledTime=12;GameStateReader.Day=2;MPServer.Sending=pid=>{if(pid=="friend")throw new IOException("simulated disconnect");};
try{LoanPeriods.Tick();}catch(IOException){}
Check(Wire.Result("loan-period-cursor")=="1"&&loans[0].Remaining==500,"failed daily payment does not advance day or loan principal");
Check(Wire.Journal().Count(p=>p.Key.StartsWith("money-out|"))==2,"both money legs prepared before a failed first send");
MPServer.Sending=null;UnityEngine.Time.unscaledTime=14;LoanPeriods.Tick();Check(loans[0].Remaining==450&&Wire.Result("loan-period-cursor")=="2"&&SaveGameManager.Current.Money==1055,"daily retry uses stored quote and finishes each leg once");
UnityEngine.Time.unscaledTime=16;LoanPeriods.Tick();Check(loans[0].Remaining==450&&SaveGameManager.Current.Money==1055,"same daily payment is not charged twice");
Wire.Remember("loan-period-cursor","1");loans[0].Remaining=500;UnityEngine.Time.unscaledTime=17;LoanPeriods.Tick();Check(loans[0].Remaining==450&&SaveGameManager.Current.Money==1055,"partially resumed day reconciles old loan principal without another payment");
GameStateReader.Day=1;UnityEngine.Time.unscaledTime=18;LoanPeriods.Tick();Check(loans[0].Remaining==450,"backwards clock does not create another loan payment");
SaveGameManager.Current=new GameInstance();RentRecovery.Reset();
var registration=new BuildingRegistration();registration.itemInstances["prior"]=new RentalItem{Name="prior",Count=2};
var rentalAttempt=RentRecovery.Begin(registration,"shop");SaveGameManager.Current.Money-=250;RentRecovery.Requested("shop","rental-op");
registration.itemInstances["prior"].Count=0;registration.itemInstances["new-layout"]=new RentalItem{Name="new"};registration.RentedByPlayer=true;registration.Layout="new";
SaveGameManager.Current.Money-=25;RentRecovery.End(rentalAttempt);RentRecovery.End(rentalAttempt);
SaveGameManager.Current=new GameInstance{Money=SaveGameManager.Current.Money,modData=new(SaveGameManager.Current.modData)};
Check(RentRecovery.Restore("rental-op",registration,out var rentalRefund)&&rentalRefund==275,"denied rent refunds actual deposit layout and first-day charges");
Check(registration.itemInstances.Count==1&&registration.itemInstances["prior"].Count==2&&!registration.RentedByPlayer&&registration.Layout=="original","denied rent restores deep original interior rather than leaving free layout items");
float beforeRefund=SaveGameManager.Current.Money;RentRecovery.Refund("rental-op",rentalRefund);RentRecovery.Refund("rental-op",rentalRefund);Check(SaveGameManager.Current.Money==beforeRefund+275,"rental refund replay credits money once by operation ID");
RentRecovery.Complete("rental-op");Check(!RentRecovery.Restore("rental-op",registration,out _),"completed rental rollback cannot refund twice");
MergerOutbox.Begin();
Action queued=()=>sent++;
object[] queueArgs={queued,null};typeof(QueueGeneration).GetMethod("Prefix",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,queueArgs);
MergerOutbox.Cancel();int beforeQueued=sent;((Action)queueArgs[0])();Check(sent==beforeQueued,"rollback cancels already queued merger mutation work");
MergerOutbox.Begin();queueArgs=new object[]{queued,null};typeof(QueueGeneration).GetMethod("Prefix",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,queueArgs);MergerOutbox.Commit();((Action)queueArgs[0])();Check(sent==beforeQueued+1,"committed merger keeps its queued work valid");
MergerOutbox.Begin();queueArgs=new object[]{queued,null};typeof(QueueGeneration).GetMethod("Prefix",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,queueArgs);MergerOutbox.Queue(()=>sent++);MergerOutbox.DeferPersist();MPSaveCoordinator.Saving=()=>throw new IOException("disk error");
beforeQueued=sent;try{MergerOutbox.Commit();}catch(IOException){}MPSaveCoordinator.Saving=null;((Action)queueArgs[0])();Check(sent==beforeQueued,"merger persistence exception releases neither messages nor queued mutations");
var interiorOld=MessageEnvelope.Create(MessageType.InteriorSnapshot,"host",new InteriorSnapshotPayload{AddressKey="shop"});
var interiorNew=MessageEnvelope.Create(MessageType.InteriorCargoSync,"host",new InteriorCargoSyncPayload{AddressKey="shop"});
Check(WorldStreams.AllowEnvelope(interiorNew)&&!WorldStreams.AllowEnvelope(interiorOld),"late full interior cannot overwrite a newer cargo packet at ingress");
Check(!WorldStreams.AllowEnvelope(interiorNew),"duplicate interior packet is refused before touching cache");
Check(WorldStreams.AllowEnvelope(null),"missing envelope retains original null guard");
result=new StorageResPayload();Wire.Ensure(result);Hooks.Calls["StorageSync.OnTakeResult"]=a=>{StorageProgress.CommitIf(false);StorageProgress.Fail();return null;};frame=StorageProgress.Begin(result);StorageProgress.Take(result);StorageProgress.End(frame);
Check(Wire.Result("storage-result|"+Wire.Meta(result).Id)==null,"refused native mutation is not marked committed");
Hooks.Calls["StorageSync.OnTakeResult"]=a=>{StorageProgress.CommitIf(true);StorageProgress.Fail();return null;};frame=StorageProgress.Begin(result);StorageProgress.Take(result);StorageProgress.End(frame);Check(Wire.Result("storage-result|"+Wire.Meta(result).Id)=="consumed","successful cargo mutation survives later UI failure without replay");
var ownerVehicle=new VehicleInstance();var ownerCargo=new BigAmbitions.Items.CargoInstance{Name="cargo",amount=10,paid=false};var childCargo=new BigAmbitions.Items.CargoInstance{Name="nested",amount=3};ownerCargo.nestedCargoInstances.Add(childCargo);ownerVehicle.cargoInstances.Add(ownerCargo);
Hooks.Calls["StorageSync.FindVehicleById"]=a=>ownerVehicle;
var ownerBaseline=CargoRollback.Owner(new StorageOpPayload{Container="vehicle",VehicleId="v"});ownerCargo.amount=2;ownerCargo.paid=true;childCargo.amount=0;ownerCargo.nestedCargoInstances.Clear();ownerVehicle.cargoInstances.Clear();ownerVehicle.cargoInstances=new();ownerBaseline.Restore();
Check(ReferenceEquals(ownerVehicle.cargoInstances[0],ownerCargo)&&ownerCargo.amount==10&&!ownerCargo.paid,"failed owner storage mutation restores original list identity amounts and paid flags");
Check(ReferenceEquals(ownerCargo.nestedCargoInstances[0],childCargo)&&childCargo.amount==3,"owner rollback restores nested cargo without serialization or asset construction");
var sellDictionary=new Dictionary<string,BigAmbitions.Items.CargoInstance>{{"item",ownerCargo}};var dictionaryBaseline=new CargoRollback();dictionaryBaseline.Dictionary(sellDictionary);sellDictionary.Clear();dictionaryBaseline.Restore();Check(ReferenceEquals(sellDictionary["item"],ownerCargo),"refused item sale restores removed dictionary entry");
bool caughtPersist=false;try{CheckedPersistence.Run(()=>CheckedPersistence.Failed(new IOException("disk full")));}catch(IOException){caughtPersist=true;}Check(caughtPersist,"swallowed disk failure is not mistaken for committed merger persistence");
caughtPersist=false;try{CheckedPersistence.Run(()=>{});}catch(IOException){caughtPersist=true;}Check(caughtPersist,"early-return persistence without a manifest write cannot release merger messages");
CheckedPersistence.Run(()=>{CheckedPersistence.ManifestStored();CheckedPersistence.Failed(new IOException("mirror disconnected after disk commit"));});Check(true,"mirror failure after manifest commit does not roll back an exposed transaction");
MergerOutbox.Begin();MergerOutbox.Queue(()=>sent++);MergerOutbox.DeferPersist();MPSaveCoordinator.StoreManifest=false;MPSaveCoordinator.Saving=()=>CheckedPersistence.Failed(new IOException("caught disk error"));beforeQueued=sent;try{MergerOutbox.Commit();}catch(IOException){}MPSaveCoordinator.StoreManifest=true;MPSaveCoordinator.Saving=null;Check(sent==beforeQueued,"merger buffer is cancelled when native writer swallows its error");
SaveGameManager.Current=new GameInstance();MoneyTransport.Reset();MPConfig.PlayerId="host";MergerSync.MyGroupId="";MergerSync.Membership.Clear();
Hooks.Calls["MPServer.StableOfPid"]=a=>(string)a[0]=="unknown"?null:a[0];
bool unknownCaught=false;try{MoneyTransport.PreparePair("host",-50,"unknown",50,"test");}catch(InvalidOperationException){unknownCaught=true;}Hooks.Calls.Remove("MPServer.StableOfPid");Check(unknownCaught&&Wire.Scan("money-out|").Length==0,"unidentified second destination leaves no orphan debit intent");
loans.Clear();loans.Add(new LoanEntry{Id="early",Borrower="friend",Lender="host",Remaining=500});MPServer.Cash["friend"]=1000;repaymentArgs=new object[]{new LoanRepayPayload{Id="early",From="friend",Amount=50},null};
Check((bool)method.Invoke(null,repaymentArgs)&&Wire.Scan("money-out|").Length==2,"early repayment prepares both money legs before either native effect");
loans[0].Remaining=450;typeof(RepaymentSafety).GetMethod("Finalizer",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new object[]{new IOException("notification failure"),repaymentArgs[1]});
repaymentArgs=new object[]{repaymentArgs[0],null};Check(!(bool)method.Invoke(null,repaymentArgs),"post-debt notification failure cannot apply the same repayment twice");
SaveGameManager.Current=new GameInstance();MoneyTransport.Reset();MoneyTransport.Context="retry-test";MoneyTransport.PreparePair("friend",-10,"third",10,"test");Wire.Remember("money-out|corrupted","{");
MPRestSync.Online.Add("third");int beforeSends=MPServer.Sent.Count;MPServer.Sending=pid=>{if(pid=="friend")throw new IOException("disconnect");};UnityEngine.Time.unscaledTime=30;MoneyTransport.Tick();MPServer.Sending=null;MPRestSync.Online.Remove("third");
Check(MPServer.Sent.Skip(beforeSends).Any(x=>x.Item1=="third"),"bad journal record or one disconnected recipient does not starve other money retries");
var incoming=new LoanOfferPayload{Id="incoming",From="friend",To="host",Principal=100};MessageEnvelope.Create(MessageType.MoneyAdjust,"host",incoming);string oldIncoming=JsonConvert.SerializeObject(incoming);HubInputs.Offer(incoming);MPHub.IncomingOffers.Add(incoming);
var refreshed=new LoanOfferPayload{Id="incoming",From="friend",To="host",Principal=120};MessageEnvelope.Create(MessageType.MoneyAdjust,"host",refreshed);bool refreshAccepted=HubInputs.Offer(refreshed);MPHub.IncomingOffers.Add(refreshed);
Check(refreshAccepted&&MPHub.IncomingOffers.Count==1&&MPHub.IncomingOffers[0].Principal==120,"offer refresh replaces pending row instead of adding another dialog");
var revoke=new LoanOfferPayload{Id="incoming",From="friend",To="host",Principal=0,State="revoke"};MessageEnvelope.Create(MessageType.MoneyAdjust,"host",revoke);
Check(HubInputs.Offer(revoke)&&!HubInputs.Offer(JsonConvert.DeserializeObject<LoanOfferPayload>(oldIncoming)),"zero-amount revocation remains valid and late pending offer cannot reopen it");
var priorLoans=new LoanStatePayload{Loans=new(){new LoanEntry{Id="older",Remaining=100}}};MessageEnvelope.Create(MessageType.MoneyAdjust,"host",priorLoans);var emptyLoans=new LoanStatePayload();MessageEnvelope.Create(MessageType.MoneyAdjust,"host",emptyLoans);
Check(HubInputs.Loans(emptyLoans)&&!HubInputs.Loans(priorLoans),"late loan snapshot cannot resurrect debt after a newer empty state");
Check(!HubInputs.Loans(new LoanStatePayload{Loans=null})&&!HubInputs.Loans(new LoanStatePayload{Loans=new(){new LoanEntry{Id="bad",Remaining=float.NaN}}}),"null or nonfinite loan list is rejected before clearing current data");
Check(!HubInputs.Loans(new LoanStatePayload{Loans=new(){new LoanEntry{Id="same"},new LoanEntry{Id="same"}}}),"duplicate loan IDs rejected");
var paced=new PacedSendQueue("test");long pacedCap=2L*SafetyCore.MaxMessage;typeof(PacedSendQueue).GetField("_bytes",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(paced,pacedCap-8);
var pacedPrefix=typeof(PacedBudget).GetMethod("Prefix",BindingFlags.NonPublic|BindingFlags.Static);object[] pacedArgs={paced,new[]{new byte[6]},"",null};pacedPrefix.Invoke(null,pacedArgs);
using(var started=new System.Threading.ManualResetEventSlim()){
 var concurrent=Task.Run(()=>{started.Set();object[] args2={paced,new[]{new byte[6]},"",null};try{pacedPrefix.Invoke(null,args2);((MonitorLease)args2[3])?.Release();return false;}catch(TargetInvocationException e)when(e.InnerException is InvalidOperationException){return true;}});
 started.Wait();Check(!concurrent.Wait(50),"second queue admission waits until first guarded mutation completes");paced.Enqueue(new[]{new byte[6]},"","test");((MonitorLease)pacedArgs[3]).Release();((MonitorLease)pacedArgs[3]).Release();Check(concurrent.GetAwaiter().GetResult()&&paced.Bytes<=pacedCap,"concurrent paced enqueues cannot jointly pass the memory limit");
}
SaveGameManager.Current=new GameInstance();MoneyTransport.Reset();Wire.Reset();var random=new Random(3682);float expectedMoney=1000;var replaySet=new List<MoneyAdjustPayload>();
for(int n=0;n<100;n++){var p=new MoneyAdjustPayload{To="host",Amount=random.Next(-20,21)};Wire.Ensure(p);expectedMoney+=p.Amount;for(int k=0;k<20;k++)replaySet.Add(JsonConvert.DeserializeObject<MoneyAdjustPayload>(JsonConvert.SerializeObject(p)));}
foreach(var p in replaySet.OrderBy(_=>random.Next()))Wire.ApplyMoney(p);Check(SaveGameManager.Current.Money==expectedMoney,"2000 shuffled duplicate money deliveries apply each logical effect once");
Check(PayloadReader.Decode<LoanStatePayload>("{")==null&&PayloadReader.Decode<LoanStatePayload>("[]")==null,"truncated or wrong-shaped payload does not escape into network callback");
Check(PayloadReader.Decode<LoanStatePayload>("{} {}")==null,"additional JSON after payload is rejected");
Check(PayloadReader.Decode<object>(new string('[',100)+new string(']',100))==null,"excessive payload JSON nesting is refused");
Check(PayloadReader.Decode<LoanStatePayload>("{\"Loans\":[]}").Loans.Count==0,"valid payload decoding preserves empty authoritative state");
MergerSync.Membership["friend"]="company";MPServer.Cash["friend"]=100;Check(MoneyTransport.NativeAvailable("friend")==1000,"native offer check uses authoritative company wallet instead of stale personal cash");MergerSync.Membership.Clear();Check(MoneyTransport.NativeAvailable("friend")==100,"personal offer check keeps native cached balance outside merger");
Wire.Assign(revoke,Wire.New());HubInputs.Offer(revoke);SaveGameManager.Current=new GameInstance{modData=new(SaveGameManager.Current.modData)};Wire.Reset();
var crossOriginPending=JsonConvert.DeserializeObject<LoanOfferPayload>(oldIncoming);Wire.Assign(crossOriginPending,new WireStamp{Id="new-packet",Origin="other-origin",World="world",Epoch="new-connection",Sequence=1});Check(!HubInputs.Offer(crossOriginPending),"terminal offer cannot reopen through another origin or connection after reload");
MPHub.IncomingOffers.Clear();MoneyTransport.ReturnPendingOffer(new LoanOfferPayload{Id="deferred",From="friend",To="host",Principal=100});Check(MPHub.IncomingOffers.Count==1&&MPHub.IncomingOffers[0].Id=="deferred","funds-deferred offer returns to inbox after AnswerOffer removed its row");
byte[] Fragment(int id,int index,int count,params byte[] data){var f=new byte[12+data.Length];f[0]=2;f[1]=66;f[2]=70;f[3]=82;Buffer.BlockCopy(BitConverter.GetBytes(id),0,f,4,4);f[8]=(byte)index;f[9]=(byte)(index>>8);f[10]=(byte)count;f[11]=(byte)(count>>8);Buffer.BlockCopy(data,0,f,12,data.Length);return f;}
var receiver=new object();byte[] full;
Check(!FragmentReceiver.Accept(receiver,new byte[]{1,2,3},out full)&&full==null,"unfragmented handshake remains available to normal decoder");
Check(FragmentReceiver.Accept(receiver,Fragment(1,1,2,3,4),out full)&&full==null,"first out-of-order fragment waits for remaining data");
FragmentReceiver.Accept(receiver,Fragment(1,1,2,3,4),out full);
Check(FragmentReceiver.Accept(receiver,Fragment(1,0,2,1,2),out full)&&full.SequenceEqual(new byte[]{1,2,3,4}),"fragment retry does not duplicate bytes and reverse order reassembles correctly");
Check(FragmentReceiver.Accept(receiver,Fragment(2,0,0),out full)&&full==null,"zero fragment count is consumed without allocation");
FragmentReceiver.Accept(receiver,Fragment(3,0,2,1),out full);
Check(FragmentReceiver.Accept(receiver,Fragment(3,1,3,2),out full)&&full==null,"inconsistent fragment counts discard partial assembly");
for(int i=0;i<32;i++)FragmentReceiver.Accept(receiver,Fragment(100+i,0,2,1),out full);
Check(FragmentReceiver.Accept(receiver,Fragment(500,0,1,9),out full)&&full==null,"fragment assembly count is bounded");
Check(FragmentReceiver.Accept(new object(),Fragment(500,0,1,9),out full)&&full.SequenceEqual(new byte[]{9}),"a full peer queue cannot block another peer handshake");
MPServer.IsRunning=false;MPSaveCoordinator.ActivePlaythroughId="";MPSaveManager.ActivePlaythrough="world";Wire.Reset();
var joinedMove=new PlayerPositionPayload{PlayerId="friend"};
var joinedEnvelope=MessageEnvelope.Create(MessageType.PlayerMove,"friend",joinedMove);
Check(Wire.Meta(joinedMove).World=="world","joined client stamps movement using the world identity received from host");
MPServer.IsRunning=true;MPSaveCoordinator.ActivePlaythroughId="world";
Check(Wire.Fresh(joinedEnvelope.GetPayload<PlayerPositionPayload>(),"player-route|friend"),"host accepts joined client movement before any client coordinated save");
MPServer.IsRunning=false;MPSaveCoordinator.ActivePlaythroughId="old-host-world";
Check(Wire.CurrentWorld=="world","client world identity ignores stale host coordinator state");
var foreignMove=new PlayerPositionPayload{PlayerId="friend"};Wire.Assign(foreignMove,new WireStamp{Id="old",World="old-host-world",Origin="friend",Epoch="old",Sequence=1});
Check(!Wire.Fresh(foreignMove,"player-route|friend"),"joined client still rejects movement from another world");
MPServer.IsRunning=true;MPSaveCoordinator.ActivePlaythroughId="world";
Console.WriteLine($"{passed} sync regression checks passed.");
sealed class RepeatedStream(long remaining):Stream{
 public override int Read(byte[] b,int o,int c){int n=(int)Math.Min(c,remaining);remaining-=n;return n;}
 public override bool CanRead=>true;public override bool CanSeek=>false;public override bool CanWrite=>false;public override long Length=>throw new NotSupportedException();public override long Position{get=>0;set=>throw new NotSupportedException();}public override void Flush(){}public override long Seek(long o,SeekOrigin s)=>throw new NotSupportedException();public override void SetLength(long v)=>throw new NotSupportedException();public override void Write(byte[] b,int o,int c)=>throw new NotSupportedException();
}
